### PR TITLE
WPGTK Support upon Init

### PR DESCRIPTION
**Pull request by VGrol**
Hi!

I wrote a quick case-if, for supporting WPGTK, as it seems to be gaining more traction and it stores the color file in a different directory.

### CODE REVIEW

**Comment by guglicap** [comment]
Hey, thanks for trying to contribute. There are a couple things I don't like about this, though. First of all, it requires manual user input, which I'd rather not have since it makes it harder to use the program in scripts (think `wal -o`, for example). Secondly, I don't really see the point of this since you can just run `ln -sf wpgtk/colors.scss ~/.config/...` after the init (and re-run `wal-discord`). At this point, I'd rather add a general colorFile flag so that we don't need flags for every theme generator that'll ever exist.

**Comment by VGrol** [comment]
That sounds entirely reasonable!
If I can manage to find some time this week, I'll try to write a quick config rewrite parameter.

Thank you for the feedback.

**Comment by guglicap** [comment]
no worries :)

**Comment by VGrol** [comment]
Any thoughts on this? 
Just quick and easy symlink cleanup and reassign.

I was thinking about adding some error checking, but the file already outputs errors by itself if the CSS file is missing or incorrect, which are quite clear in the fact that they're related to the CSS file.

EDIT: I forgot to mention that I added the other options from the wiki to the help display.

**Comment by guglicap** [comment]
Hmm, a few things: 
1. colorDir should be named colorFile as that's what it is
2. you don't need the if and the `rm` lines as `ln -sf` just overrides the existing symlink
3. I'd move the relevant `ln -sf` line to `setup` as it does not belong in `main`

The rest looks okay. Also be sure to check the script with `shellcheck` once you're done :)

**Comment by VGrol** [comment]
I deliberately opted to not implement it in setup,
mostly because putting it there means it would only take the argument when there is something that triggers the setup function.
I don't personally think there is much value in an option that is only configurable at first time setup, without prompting the user to do so.

I could move it away from the main loop, that'd make sense. but I could only see that working with having it in its own function, which in turn gets invoked by the -c flag.
Any thoughts on that?

**Comment by guglicap** [comment]
But the thing is, it actually only makes sense during setup. Otherwise `wal -c` would just be a wrapper around `ln -sf`, and at that point it's just better to not implement it and use `ln` directly. Though you're right, it's not very elegant to have a command line option which will be ignored in most cases. Maybe an environment variable would be better instead?

**Comment by VGrol** [comment]
I'll have to think a bit on how to best implement it.

Unless we expand functionality of ``wal -c`` to auto detect WPG/WAL or prompt based on an invocation of ``-c``, it'll always be an ln -sf wrapper, no matter if it sits in the main or setup loop.

Perhaps it'd be beneficial to rewrite setup, so that it checks for both the wpg and wal file, and if it finds both or none, it could default to wal or prompt the user to select one?

**Comment by guglicap** [comment]
I wouldn't really say rewrite it, I'd just add a `|| ln -sf <wpgtk colors> <wal-discord colors.scss>` after [this](https://github.com/guglicap/wal-discord/blob/dd8edea82f2d46628c2800cbf12c2f4381b82102/wal-discord#L49) line, but that'd only work if the user is using only wpgtk and not also wal.  
I don't like your first proposal; as I said, I'd avoid user input and at this point it's pretty clear to me we don't want to add a `-c` flag either.

**Comment by VGrol** [comment]
Apologies for the delay, life has been busy.
I figured you wanted to avoid user input. I'm honestly not to keen on any implementation that doesn't cover all use cases, but for now, I think it is best to leave it up to users in dual-use case scenarios.

I'm considering a basic 
```
if [[ -n <wpgtk dir/wpgtk colors.scss> ]]; then 
ln -sf <wpgtk colors.scss> <wal-discord colors.scss>

else
ln -sf <wal colors.scss> <wal-discord colors.scss>
```

Though there are a few ways to do that.

- The above, a basic ELIF loop, picking wpgtk if available.
- A more slightly more advanced loop, statement to check if both wpg/wal are present and then providing an exception.


This exception itself could be one of the following.
   - Default Wal color file
   - Default WPG color file
   - Check file modification timestamps and select the most recent.
   - Potential output a system notification/console output that mentions it defaulted to WPG or Wal, and that if this is undesired, the user themselves can run ln -sf <color file of choice> instead.

**Comment by guglicap** [comment]
Yeah I think checking if both are present and then defaulting to the most recent is a nice solution. In this case, as you said, we should output a notice saying that it's defaulted to wal / wpg and to run `ln` to switch.

**Comment by VGrol** [comment]
It seems you've beat me to it with the rewrite of the -help output, haha.
Aside from the arbitrary edits on some of the spacing, this should be a quick implementation for what we've discussed.

I initially considered adding an error if neither files turned up, but my evidently I ended up deciding against this due to this going against the original assumption that the WAL file is present to begin with.

**Comment by guglicap** [comment]
Looks fine to me, I just slimmed down the colors logic. Merging, thanks for your work :)

**Pull request merged**
