### PR TITLE
Secondary colour accent & Syntax highlighting

### LINKED ISSUE #24: [Enhancement] Change code highlight colors
Discord allows you use markdown to include syntax highlighted code, like

```c
for(int i = 0; i < 10; i++){
    printf("This is highlighted");
}
```
Would it be difficult to modify the `css` to highlight code from the `wal` color pallet? 

I have done something similar in [vim.reaper](https://github.com/GideonWolfe/vim.reaper#markdown) with the markdown preview vim plugin.

### PR DESCRIPTION
**Pull request by VGrol**
Request should fulfill #24 
This turned out to be far easier than I expected. Turns out that discord is being sensible and only using ~6 global variables for all different languages, instead of manually supporting each language.

### CODE REVIEW

**Comment by VGrol** [comment]
oops, forgot to capitalize the variables in the backend. 
fixed as of 54a8614

**Comment by guglicap** [comment]
I'll be testing it out, would you mind squashing one commit like "feat: code highlight colors" and force pushing the branch? Thanks.

**Comment by VGrol** [comment]
@guglicap 
Done.

as I initially said, only the back ends themselves should need configuring/making the colours work.
I haven't gotten to test all the code syntax highlighting, so I might've missed one variable but I doubt it. Across a dozen languages it all seems to come back to these.

**Comment by guglicap** [comment]
@VGrol Thanks, tested it and looking good. I pushed some updates to master in the meanwhile so you should probably rebase and update the `@version 0.0.1` comment in master.scss to `@version 0.0.2`. I'm trying to make the project a little more structured now that more people are using it, or working on it. For this same reason, please change the commit message to have the prefix "feat:", short for "feature". Hope you understand, thank you.

**Comment by VGrol** [comment]
@guglicap Remind me to not do branch management without my morning coffee.
That mess of rebasing, force pushing aside.... 

Should be compliant to your requests.
Dear lord I need coffee.

**Comment by guglicap** [comment]
@VGrol ahah, don't worry. I can relate. Thanks, merging.

**Pull request merged**
